---

- name: 'Install mariadb'
  tags: mariadb
  apt:
    name: mariadb
    state: present

- name: 'Enable mariadb service'
  tags: mariadb
  service: name=mariadb state=started enabled=yes

- name: Allow incoming database connection
  ufw:
    rule: allow
    port: 3306
