---
# This role contains common plays that will run on all nodes.

- name: Remove official docker via apt
  tags: dockersetup
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

# Install dependencies for docker CE installation
- name: Add docker CE installation deps
  tags: dockersetup
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - python-pip
    - python-dev
    - build-essential
    - software-properties-common

- name: Add docker apt signing key
  tags: dockersetup
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add the docker repository
- name: Add the docker CE repository
  tags: dockersetup
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }}  stable
    state: present

- name: Install docker CE {{ docker_ver }}
  tags: dockersetup
  apt:
    name: docker-ce={{ docker_ver }}
    state: present

- name: Start the docker service
  tags: dockersetup
  service: name=docker state=started enabled=yes

- name: Install docker python dependencies
  tags: dockersetup
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker>=2.7.0"
    - "docker-compose==1.9.0"

- name: Fix docker-compose
  tags: dockersetup
  shell: 'pip install --upgrade docker-py'
