---

- name: Initial setup of admin tools
  hosts: all
  tasks:
    - name: Install a file manager
      apt:
        package: mc
        state: present
    - name: Install process explorer
      apt:
        package: htop
        state: present

- name: Add basic security
  hosts: all
  tasks:
    - name: Install firewall
      tags: security
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ufw

    - name: Reset Firewall rules
      when: thorough is defined and thorough
      tags: security
      shell: "ufw disable && yes | ufw reset"

    - name: Turn on Firewall logging
      tags: security
      ufw:
        logging: on

    - name: Deny all incoming connections
      tags: security
      ufw:
        state: enabled
        policy: deny

    - name: Allow incoming ssh
      tags: security
      ufw:
        rule: allow
        port: 22
