---

- name: Setup basic nginx on host
  hosts: client1_servers
  vars:
    - companyName: "JustRocket"
  tasks:
    - name: 'Install nginx'
      apt:
        name: nginx
        state: present
    - name: 'Enable nginx service'
      service: name=nginx state=started enabled=yes
    - name: 'Copy robots.txt'
      copy:
        src: files/robots.txt
        dest: /var/www/html/robots.txt
    - name: 'Copy index.html template'
      template:
        src: files/index.html.template
        dest: /var/www/html/index.html
    - name: 'Allow firewal 80'
      ufw:
        rule: allow
        port: 80

- name: Add shell welcome
  hosts: client1_servers
  tasks:
    - name: Init motd
      tags: init, motd
      template:
        dest: /etc/motd
        src: files/motd.template
